<?php

class SurveyController extends Controller
{

    public function actionForm($surveyId)
    {
        $survey = Survey::model()->findByPk($surveyId);
        $this->render('form', array(
            'survey' => $survey,
        ));
    }

    public function actionSurveys()
    {
        ?>
        function loadYleWebPollResources(){if(typeof jQuery!='undefined'){if(typeof(jQuery().cookie)==='undefined'){jQuery.cookie=function(name,value,options){if(typeof value!='undefined'){options=options||{};if(value===null){value='';options=jQuery.extend({},options);options.expires=-1;}
        var expires='';if(options.expires&&(typeof options.expires=='number'||options.expires.toUTCString)){var date;if(typeof options.expires=='number'){date=new Date();date.setTime(date.getTime()+(options.expires*24*60*60*1000));}else{date=options.expires;}
        expires='; expires='+date.toUTCString();}
        var path=options.path?'; path='+(options.path):'';var domain=options.domain?'; domain='+(options.domain):'';var secure=options.secure?'; secure':'';document.cookie=[name,'=',encodeURIComponent(value),expires,path,domain,secure].join('');}else{var cookieValue=null;if(document.cookie&&document.cookie!=''){var cookies=document.cookie.split(';');for(var i=0;i<cookies.length;i++){var cookie=jQuery.trim(cookies[i]);if(cookie.substring(0,name.length+1)==(name+'=')){cookieValue=decodeURIComponent(cookie.substring(name.length+1));break;}}}
            return cookieValue;}};}
            (function($){$.yleWebPoll=function(el,options){var base=this;base.$el=$(el);base.el=el;base.$el.data("yleWebPoll",base);base.sessionCookie="sessionCookie";base.userIdCookie="webropoll_id";base.init=function(){base.options=$.extend({},$.yleWebPoll.defaultOptions,options);base.webropollSurveyIdCookie=base.options.siteURL;base.launchSurveyByFreq(function(){base.setUserIdCookie(base.userIdCookie);base.setCookie(base.webropollSurveyIdCookie,"yleWebPoll");base.viewLayer(base.getWebroPollUrl());})};base.setUserIdCookie=function(userIdCookie){if(!base.isCookie(userIdCookie)){var userId=base.randomNumber(600000);userId+=new Date().getTime();base.setCookie(userIdCookie,userId);}};base.getWebroPollUrl=function(){var url=base.options.formURL,urlParams=base.options.urlParams,urlParamsArray=[];if(url!=''){for(key in urlParams){if(urlParams[key]!='undefined'&&urlParams[key]!=null&&urlParams[key]!=''){urlParamsArray.push(key+'='+urlParams[key]);}}
            if(url.match(/\?/)){return url+'&'+urlParamsArray.join('&');}else{return url+'?'+urlParamsArray.join('&');}}else{base.log('YLE.fi - Webropol error '+e);}};base.isCookie=function(cookie){var found=false;if($.cookie(cookie)!=null){found=true;}
            return found;};base.isFreqPoll=function(){$.cookie(base.sessionCookie,base.sessionCookie,{path:base.options.path});var viewLayer=false;var randomNumber=base.randomNumber(base.options.displayFrequency);var freqView=randomNumber/base.options.displayFrequency;base.debug("Arvonnassa",freqView);if(freqView==1){viewLayer=true;}
            return viewLayer;};base.viewLayer=function(url){base.$el.append('<h1 style="display: block;font-size: 2em;font-weight: bold; margin: 0.67em 0;border:none;">'+base.options.title+'</h1><p style="color:#000;">'+base.options.text+'</p><a href="#" id="yleWebPoll-yes">'+base.options.linkYes+'</a><a href="#" id="yleWebPoll-no">'+base.options.linkNo+'</a>');var cssObj={'background-color':'#fff','position':'absolute','font-family':'arial','font-size':'12px','color':'#000','top':'20%','max-width':'500px','width':'80%','z-index':'9999','padding':'20px','border':'solid 1px #000','-moz-box-shadow':'5px 5px 7px #888','-webkit-box-shadow':'5px 5px 7px #888','box-shadow':'5px 5px 7px #888'};base.$el.css(cssObj);var leftMargin=($(window).width()/2)-(base.$el.width()/2);base.$el.css('left',leftMargin+'px');var linkCSS={'-moz-border-radius':'5px','-webkit-border-radius':'5px','border-radius':'5px','background-color':'#3993D1','color':'#FFFFFF','font-size':'12px','font-weight':'bold','margin-right':'10px','padding':'3px 10px','text-decoration':'none'};base.$el.find('a').css(linkCSS);base.$el.fadeIn();base.$el.find('#yleWebPoll-yes').click(function(e){e.preventDefault();base.$el.fadeOut();var popunder=window.open(url,'YLE','toolbar=0,location=1,directories=1,status=1,menubar=0,scrollbars=1,resizable=1');popunder.blur();window.focus();});base.$el.find('#yleWebPoll-no').click(function(e){e.preventDefault();base.$el.fadeOut();});};base.launchSurveyByFreq=function(callback){if(!base.isCookie(base.sessionCookie)&&!base.isCookie(base.webropollSurveyIdCookie)||base.options.debug){if(base.isFreqPoll()||base.options.debug){callback();}else{return false;}}};base.getCookie=function(cookieName){return $.cookie(cookieName);};base.setCookie=function(cookie,str){var expirationDate=new Date;expirationDate.setMonth(expirationDate.getMonth()+6);$.cookie(cookie,str,{expires:expirationDate,path:base.options.path});base.debug("Cookie vanhenee",expirationDate);};base.randomNumber=function(freq){return Math.floor(Math.random()*freq)+1;};base.debug=function(msg,content){if(base.options.debug&&typeof console!=="undefined"){console.log(msg+": "+content);}};base.init();};$.yleWebPoll.defaultOptions={title:"Tervetuloa!",text:"Mielipiteesi on meille tärkeä: ottaisitko osaa lyhyeen kävijäkyselyyn käyntisi jälkeen?<br/><br/>Osallistuminen on helppoa, ja kysymme vain muutaman nopean kysymyksen. Paina \"Kyllä!\" -nappia, ja jatka käyntiäsi normaalisti. Avaamme kyselyn toiseen ikkunaan, jonka löydät työpöydältäsi tämän ikkunan alta käynnin jälkeen.<br/><br/>Kiitos osallistumisestasi!",linkNo:"Ei kiitos",linkYes:"Kyllä!",path:"/",formURL:null,debug:true,displayFrequency:10};$.fn.yleWebPoll=function(options){var el=this.data("yleWebPoll");if(el){return el;}
            return this.each(function(){(new $.yleWebPoll(this,options));});};})(jQuery);(function($){function init(siteConfs){try{var currentPath=getSiteRoot(),currentHostname=window.location.hostname,currentUrl=currentHostname+currentPath,currentCategory=$('body').attr('data-yleWebpollCategory'),currentSiteConf=getCurrentSiteConf(siteConfs.continousPollList,currentUrl,currentCategory);if(currentSiteConf){launchPlugin(currentSiteConf,siteConfs.continousPollConf);}else{return false;}}catch(e){if(typeof console!=="undefined"){console.log('YLE.fi, Webropol-bootstrap error: '+e);}}}
            function launchPlugin(currentSiteConf,formSettings){var pluginOptions=mapOptions(currentSiteConf,formSettings);$('<div id="yleWebPoll" style="display:none;"></div>').appendTo('body').yleWebPoll(pluginOptions);}
            function mapOptions(currentSiteConf,formSettings){return{path:currentSiteConf.currentPath,formURL:formSettings.formURL,siteURL:currentSiteConf.siteURL,urlParams:{pollID:currentSiteConf.id},displayFrequency:currentSiteConf.freq};}
            function getCurrentSiteConf(siteConf,currentUrl,currentCategory){var currentSiteConf,lastSlashRegx=/\/$/;for(i in siteConf){var siteUrl=siteConf[i].siteURL,siteUrlObj=getSiteConfUrlLocation(siteUrl);siteUrl=siteUrlObj.domain+siteUrlObj.path;siteUrl=siteUrl.replace(lastSlashRegx,'');currentUrl=currentUrl.replace(lastSlashRegx,'');if(typeof(currentCategory)!='undefined'){if(currentCategory==siteConf[i].category){currentSiteConf=siteConf[i];currentSiteConf.currentPath='/';break;}}
            else{if((siteUrl=='www.yle.fi'&&currentUrl=='www.yle.fi')||(siteUrl=='yle.fi'&&currentUrl=='yle.fi')){currentSiteConf=siteConf[i];currentSiteConf.currentPath='/';break;}else{console.log(currentUrl);console.log(siteUrl);if(currentUrl.match(siteUrl)&&siteUrl!='yle.fi'&&siteUrl!='www.yle.fi'&&siteUrl!=''){currentSiteConf=siteConf[i];currentSiteConf.currentPath=siteUrlObj.path;break;}}}}
            return currentSiteConf||false;}
            function getSiteRoot(){return window.location.pathname;}
            function getCurrentComscoreCategory(){if(typeof(window.ns_pixelUrl)!=='undefined'){return window.ns_pixelUrl.replace(/^.*\?/,'').replace(/&.*$/,'');}else{return false;}}
            function getSiteConfUrlLocation(siteConfUrl){var url=siteConfUrl.replace(/http:\/\/|https:\/\//,""),urlSplit=url.split('/'),siteConfLocation={};siteConfLocation.domain=urlSplit[0];siteConfLocation.path='/'+(urlSplit[1]||'');return siteConfLocation;}
            var conf=window.YLEWebPollsConfig||{};init(conf);})(jQuery);}}
            if(window.attachEvent){window.attachEvent('onload',loadYleWebPollResources);}else{window.addEventListener('load',loadYleWebPollResources,false);}var YLEWebPollsConfig={"continousPollList":[{"id":"136074972951621","siteTitle":"Areena","siteURL":"http://localhost/rullaava-kysely-test","freq":50,"category":"areenas","motivesList":"5.7.10.11.12.13.14.19.21.22.23","comScoreAccount":"areenas"},{"id":"136074972951631","siteTitle":"Elävä Arkisto","siteURL":"http://yle.fi/elavaarkisto/index.html","freq":10,"category":"Elävä Arkisto","motivesList":"12.13.14.15.16.17.18","comScoreAccount":"test"},{"id":"1361346803406","siteTitle":"Yle Puhe","siteURL":"http://yle.fi/puhe/","freq":1,"category":"puhe","motivesList":"4.6.13.14.15.16.17.18.19","comScoreAccount":"puhe"}],"continousPollConf":{"googleKey":"dEh0cUdCM280b3dIRWtIeENIUHlkaGc6MQ","motives":{"1":"Yle Uutiset on kotisivuni","2":"Tulin lukemaan uutisia","3":"Tulin lukemaan urheilu-uutisia","4":"Tulin lukemaan juttuja","5":"Tulin katsomaan mitä uutta on tarjolla","6":"Tulin katsomaan ohjelmatietoja","7":"Tulin katsomaan/kuuntelemaan uutislähetyksiä","8":"Tulin katsomaan säätiedot","9":"Tulin katsomaan urheilutuloksia","10":"Tulin katsomaan/kuuntelemaan urheilulähetyksiä","11":"Tulin katsomaan tv:stä tulleen ohjelman","12":"Tulin katsomaan suoraa tv-lähetystä","13":"Tulin kuuntelemaan radiosta tulleen ohjelman","14":"Tulin kuuntelemaan suoraa radiolähetystä","15":"Tulin osallistumaan shoutbox-keskusteluun","16":"Tulin jättämään kommentin keskusteluun","17":"Tulin etsimään tietoa kanavasta","18":"Tulin etsimään tietoa jostakin aiheesta","19":"Tulin selailemaan/viettämään aikaa","20":"Nostalgia, vanhojen muistelu","21":"Kiinnostus henkilöön","22":"Kiinnostus ohjelmaa kohtaan","23":"Kiinnostus ilmiöön","24":"Tulin osallistumaan ohjelmaan","25":"Tulin etsimään tietoa soitetusta musiikista"},"formURL":"http://yle.fi/global/kysely/index.html"}}
        <?php
        }

    }