<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'motive.create' => 'Luo uusi käyntimotiivi',
  'motive.create.heading' => 'Uusi käyntimotiivi',
  'motive.index.heading' => 'Käyntimotiivit',
  'motive.motive' => 'Käyntimotiivi',
  'motive.update.heading' => 'Muokkaa käyntimotiivia',
  'survey.category' => '',
  'survey.comscore' => '',
  'survey.create.heading' => 'Uusi kysely',
  'survey.frequency' => '',
  'survey.update.heading' => 'Muokkaa kyselyä',
  'survey.url' => '',
  'delete' => 'Poista',
  'motives' => 'Motiivikysymykset',
  'save' => 'Tallenna',
  'survey.active' => 'Aktivoitu',
  'survey.active.off' => 'Pois päältä',
  'survey.active.on' => 'Päällä',
  'survey.create' => 'Luo uusi kysely',
  'survey.index.heading' => 'Kyselyt',
  'survey.name' => 'Nimi',
  'surveys' => 'Kyselyt',
  'update' => 'Muokkaa',
);
