<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'thanks' => 'Kiitos',
  'answer.interest.0' => 'Erittäin kiinnostava',
  'answer.interest.1' => 'Kiinnostava',
  'answer.interest.2' => 'Melko kiinnostava',
  'answer.interest.3' => 'Ei kovin kiinnostava',
  'answer.interest.4' => 'Ei kiinnostava',
  'answer.interest.5' => 'Ei lainkaan kiinnostava',
  'answer.interest.6' => 'En tunne palvelua',
  'answer.recommend.1' => 'Erittäin epätodennäköisesti',
  'answer.recommend.10' => 'Erittäin todennäköisesti',
  'answer.users.4' => 'tai useampi',
  'choose' => 'Valitse',
  'no' => 'Ei',
  'survey.failure_text.question' => 'Jos ei, miksi ei?',
  'survey.feedback.question' => 'Onko mielessäsi muuta palautetta liittyen {site} -sivustoon?',
  'survey.gender.female' => 'Nainen',
  'survey.gender.male' => 'Mies',
  'survey.gender.question' => 'Sukupuolesi',
  'survey.heading' => 'Millainen oli vierailusi {site} -palvelussamme?',
  'survey.interest.question' => 'Mitä mieltä olet {site} -palvelustamme yleensä?',
  'survey.motive.question' => 'Mikä seuraavista vaihtoehdoista kuvaa parhaiten käyntisi tarkoitusta tänään?',
  'survey.notice.user-information' => 'Kerro vielä pari asiaa itsestäsi. Antamasi tiedot ovat anonyymeja eli niitä ei voida yhdistää sinuun, mutta ne auttavat meitä parantamaan palveluamme.',
  'survey.recommend.question' => 'Suosittelisitko {site} -sivustoamme ystävällesi tai kollegallesi?',
  'survey.submit' => 'Lähetä vastaus',
  'survey.success.question' => 'Oliko käyntisi {site} -sivulla onnistunut?',
  'survey.users.question' => 'Kuinka moni henkilö taloudessanne käyttää laitetta, jolla vastaat kyselyyn?',
  'survey.year_of_birth.question' => 'Syntymävuotesi',
  'yes' => 'Kyllä',
);
