<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    'title' => 'Tervetuloa',
    'row1' => 'Mielipiteesi on meille tärkeä.',
    'row2' => 'Ottaisitko osaa lyhyeen kävijäkyselyyn käyntisi jälkeen?',
    'row3' => 'Osallistuminen on helppoa, ja kysymme vain muutaman nopean kysymyksen. Käytämme tietoja Ylen verkkopalveluiden parantamiseen. Tallennetut tiedot ovat täysin anonyymejä.',
    'row4' => 'Avaamme kyselyn uuteen välilehteen. Voit suorittaa vierailusi loppuun ja vastata kyselyyn sen jälkeen.',
    'row5' => 'Kiitos osallistumisestasi!',
    'yes' => 'Kyllä',
    'no' => 'Ei',
);
