<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '7 days' => '7 Päivää',
  'NPS' => 'NPS',
  'age' => 'Ikä',
  'chart.age' => 'Ikäjakauma',
  'chart.gender' => 'Sukupuolijakauma',
  'compare.no' => 'Ei vertailujaksoa',
  'compare.period' => 'Edellinen jakso',
  'compare.year' => 'Edellinen vuosi',
  'detractor' => 'Arvostelija',
  'failed only' => 'Vain epäonnistuneet',
  'failure reason' => 'Käynnin epäonnistumisen syy',
  'female' => 'Nainen',
  'filter.select all' => 'Valitse kaikki',
  'gender' => 'Sukupuoli',
  'interest' => 'Kiinnostus',
  'male' => 'Mies',
  'max' => 'Maksimi',
  'min' => 'Minimi',
  'month' => 'Kuukausi',
  'negative' => 'Negatiivinen',
  'neutral' => 'Neutraali',
  'next' => 'Seuraava',
  'number of answers' => 'Vastausten lukumäärä',
  'open feedback' => 'Avoin palaute',
  'passive' => 'Passiivinen',
  'positive' => 'Positiivinen',
  'previous' => 'Edellinen',
  'promoter' => 'Suosittelija',
  'recommend' => 'Suosittelu',
  'sentiment' => 'Sentimentti',
  'site' => 'Palvelu',
  'success' => 'Onnistuminen',
  'text only' => 'Vain tekstilliset',
  'topics' => 'Aihealueet',
  'visit motive' => 'Käynnin motiivi',
  'week' => 'Viikko',
  'year' => 'Vuosi',
  'years' => 'vuotta',
);
