<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'submitting' => '',
  'survey.success.later' => '',
  'survey.success.other' => '',
  'answer.interest.0' => 'Mycket intressant',
  'answer.interest.1' => 'Intressant',
  'answer.interest.2' => 'Ganska intressant',
  'answer.interest.3' => 'Inte så intressant',
  'answer.interest.4' => 'Ointressant',
  'answer.interest.5' => 'Inte alls intressant',
  'answer.interest.6' => 'Jag inte bekant med tjänsten',
  'answer.recommend.1' => 'Mycket osannolikt',
  'answer.recommend.10' => 'Mycket osannolikt',
  'answer.users.4' => 'eller fler',
  'choose' => 'Välj',
  'no' => 'Nej',
  'survey.failure_text.question' => 'Om inte, varför?',
  'survey.feedback.question' => 'Har du annan feedback du önskar ge åt {site}?',
  'survey.gender.female' => 'Kvinna',
  'survey.gender.male' => 'Man',
  'survey.gender.question' => 'Kön',
  'survey.heading' => 'Hurdant var ditt besök på {site}?',
  'survey.interest.question' => 'Vilken är din åsikt om {site} i allmänhet?',
  'survey.motive.question' => 'Vilket av alternativen beskriver bäst anledningen till ditt besök i dag?',
  'survey.notice.user-information' => 'Berätta ännu några saker om dig själv. Dina uppgifter förblir anonyma, alltså kan de inte kopplas till dig utan de hjälper oss att förbättra tjänsten.',
  'survey.recommend.question' => 'Skulle du rekommendera {site} för din vän eller kollega?',
  'survey.submit' => 'Skicka svar',
  'survey.success.question' => 'Var ditt besök på {site} lyckat?',
  'survey.users.question' => 'Hur många personer i ditt hushåll använder apparaten som du använder för att besvara enkäten?',
  'survey.year_of_birth.question' => 'Födelseår',
  'thanks' => 'Tack',
  'yes' => 'Ja',
);
