<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
  'title' => 'Välkommen',
    'row1' => 'Din åsikt är viktig för oss.',
    'row2' => 'Vill du delta i en kort besökarenkät efter ditt besök? ',
    'row3' => 'Det är lätt att delta och vi ställer bara några snabba frågor.',
    'row4' => 'Vi öpppnar enkäten i en ny flik. Du kan i lugn och ro slutföra ditt besök och besvara enkäten efter det.',
    'row5' => 'Tack för ditt bidrag!',
    'yes' => 'Ja',
    'no' => 'Nej',

);