<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'NPS' => '',
  'age' => '',
  'compare.no' => '',
  'compare.period' => '',
  'compare.year' => '',
  'detractor' => '',
  'female' => '',
  'filter.select all' => '',
  'gender' => '',
  'interest' => '',
  'male' => '',
  'month' => '',
  'negative' => '',
  'neutral' => '',
  'next' => '',
  'number of answers' => '',
  'passive' => '',
  'positive' => '',
  'previous' => '',
  'promoter' => '',
  'sentiment' => '',
  'success' => '',
  'topics' => '',
  'week' => '',
  'year' => '',
);
